project_id = "eabidmxaasaxulebfwlh"

[functions.save-contact]
verify_jwt = true

[functions.sync-extension-data]
verify_jwt = true

[functions.get-user-contacts]
verify_jwt = true

[functions.update-contact]
verify_jwt = true

[functions.delete-contact]
verify_jwt = true

[functions.enrich-contact]
verify_jwt = true

[functions.validate-scheduler-links]
verify_jwt = true

[functions.export-contacts]
verify_jwt = true

[functions.import-contacts]
verify_jwt = true