// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eabidmxaasaxulebfwlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhYmlkbXhhYXNheHVsZWJmd2xoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMzA1MDgsImV4cCI6MjA3MjYwNjUwOH0.L2GSWwi58qyZ8sIvLaqR_W3bHyojel3Txf-bEMuNGIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});